- internal/marshal/encode.go
While thinking about whether or not it would be difficult to add
EncodeIQ and EncodeIQElement methods to Session I realized that I
wouldn't be able to implement them in terms of SendIQ and SendIQ element
because these use a token reader based API as opposed to the token
writer based API used by the functions in Marshal. However, internally
the marshal functions create a token reader and then copy from it into
the writer, so by exposing this functionality we can make it possible to
create reader or writer based functionality with the marshal package.
> internal/marshal: add TokenReader API

- design/42_integration_testing.md
> design: adds a design doc for integration testing

- .builds/ci.yml
- .builds/dco.yml
- .builds/sync.yml
Sync the repo to GitHub any time we push to SourceHut.
> Sync to GitHub

- .builds/ci.yml
- .builds/dco.yml
> .builds: default to SourceHut repo for CI

- CHANGELOG.md
- conn.go
- features.go
- negotiator.go
- sasl.go
- sasl2/sasl.go
- session.go
This needs a test before it can be merged.
Fixes #45
> Fix SCRAM-*-PLUS with TeeIn/TeeOut

- design/110_mam.md
- design/template.md
> design: add proposal for MAM

- history/query.go
- history/query_test.go
Implements unmarshaling of history queries and adds tests for both marshaling and unmarshaling.
> history: support unmarshaling queries

- history/query.go
Previously there was no way to support the "before" and "after" queries
that are a part of Result Set Management.
This was because they are more or less redundant with after-id and
before-id as far as I can tell.
However, since it turns out that not much supports mam:2#extended (and
thus before-id and after-id queries) that the older before/after filters
can be used alongside start/end time based queries to effectively
emulate before-id and after-id.
Though it still feels like they're more or less the same thing and I
don't fully understand the difference, this adds support fore
before/after queries.
> history: support paging before and after

- CHANGELOG.md
- internal/ns/ns.go
- stanza/error.go
- stanza/stanza.go
Also remove ns.Stanza from internal/ns.
Updates #112
Fixes #149
> stanza: replace ns.Stanza with NSError

- CHANGELOG.md
- bind.go
- blocklist/blocking_test.go
- carbons/handler_test.go
- delay/delay_test.go
- disco/handler_test.go
- internal/ns/ns.go
- internal/stream/stream.go
- internal/stream/stream_test.go
- internal/xmpptest/session.go
- muc/integration_test.go
- muc/muc_test.go
- muc/room_integration_test.go
- muc/room_test.go
- mux/mux_test.go
- negotiator.go
- ping/integration_test.go
- ping/ping_test.go
- receipts/receipts.go
- receipts/receipts_test.go
- roster/roster_test.go
- session.go
- session_message.go
- session_presence.go
- stanza/id_test.go
- stanza/stanza.go
- styling/disable.go
- xtime/time_test.go
internal/ns: remove Client and Server constants
all: update to replace internal/ns with stanza constants
Fixes #147
Fixes #148
Fixes #112
> stanza: add NSClient and NSServer constants

- forward/forward_test.go
Signed-off-by: TAKI MEKHALFA <takiedd.mekhalfa@gmail.com>
> forward: fix issue with error formatting in tests

- forward/forward_test.go
Add some tests to check that forward.Unwrap returns an error if the first token does not correspond to the specific <forwarded xmlns='urn:xmpp:forward:0'>.
Signed-off-by: TAKI MEKHALFA <takiedd.mekhalfa@gmail.com>
> forward: test Unwrap when errors are expected

- .builds/integration.yml
> .builds: disable mcabber, ejabberd integration tests

- internal/integration/integration.go
Fixing a handful of small typos.
> internal/integration: fix several typos in docs

- internal/integration/prosody/config.go
- internal/integration/prosody/prosody.cfg.lua.tmpl
Pull the config out into a file and embed it for easier editing.
> internal/integration/prosody: extract config

- session.go
Handlers take out a read and a write lock on the stream. These locks are
not released until the handler returns, resulting in a great deal of
lock contention even if the handler never ends up reading or writing.
This patch minimizes lock contention in two ways:
For the reader we limit the handler to reading a single top level XML
element. This means that as soon as reading the element is complete we
can go ahead and release the lock. In the worst case (the handler
doesn't completely read the element) we have the same issue. In the best
(and likely most common case), the handler decodes the entire element
immediately and the lock can be released before the main body of the
handler begins.
For writes the solution is similar: we defer taking the lock out until
the first call to EncodeToken. …
> xmpp: minimize lock contention on handlers

- examples/msgrepl/main.go
Make sending messages easier by remembering the last address and
allowing bare strings so we don't have to type it every single time.
Also support joining and leaving MUCs and display the nickname of the
sender if receiving a message from a MUC channel.
> examples/msgrepl: simplify UX and add MUC support

- ibb/integration_test.go
- ibb/slixmpp_integration_test.py
Add some integration tests against slixmpp.
> ibb: test against slixmpp

- design/171_caps.md
Add API for getting information about the servers capabilities from the
stream feature as well as a handler that can be used to respond to
incoming caps hashes.
> design: update caps design doc

- design/266_crypto.md
> design: add crypto design doc
