mellium/xmpp

.builds/freebsd.yml

Add a check to CI to make sure that `go mod tidy` is run on all patches and PRs.
The changes to `go.mod` will be removed before merge, they are just there so that the first CI run will fail to validate the changes.

.builds: validate that `go mod tidy' has been run

---

dial/dial.go
dial/dial_test.go

Experimenting with using a port provided in the JID. I am still unsure what the behavior should be when an SRV lookup would return a port, but a port is also provided in the JID.

dial: use port if provided in JID

---

dial/dial_test.go
dial/server_test.go

Tests for the [`dial`](https://godoc.org/mellium.im/xmpp/dial) package were sadly incomplete. This is the start of a way to test the public interface that can replace some of the tests for internal components and do a better job of testing end-to-end without requiring actual integration tests that need external resources.
It is rather slow and requires a lot of extra testing infrastructure that makes me a bit nervous, so I'm unsure if I want to merge it yet.

dial: check DNS questions in tests

---

.builds/freebsd.yml
dial/dial_test.go
dial/server_test.go

The append is sometimes happening after the tests have completed,
resulting in a failure. Wait until the DNS server goroutine shuts down
to check the test results.

dial: wait for server to shut down before finishing tests

---

uri/export_test.go
uri/iri.go
uri/iri_test.go

Implements a parser for XMPP IRIs (see [RFC 3987]) and URIs ([RFC 3986]) as defined in [RFC 5122]. Because it piggybacks on [`net/url`], it may make a handful of invalid assumptions but it should parse most common XMPP IRI's. It also needs a lot of work on the efficiency front to prevent having to escape and unescape repeatedly.
[RFC 3986]: https://tools.ietf.org/html/rfc3986
[RFC 3987]: https://tools.ietf.org/html/rfc3987
[RFC 5122]: https://tools.ietf.org/html/rfc5122
[`net/url`]: https://golang.org/pkg/net/url/

uri: new package implementing XMPP URI's and IRI's

---

design/0001_xep0047_in-band_bytestreams.md
design/README.md

**Author(s):** Sam Whited  
**Last updated:** 2020-01-08  
**Status:** thinking
An API design is proposed for [XEP-0047: In-Band Bytestreams][XEP-0047].
[XEP-0047]: https://xmpp.org/extensions/xep-0047.html
In-Band Bytestreams (IBB) is the lowest common denominator for transferring
binary data such as files over XMPP streams.
It is slow and inefficient, but also simple and almost universally supported.
Implementing it will allow us to begin experimenting with multiplexing data over
XMPP streams and provide us with experience designing and implementing file
transfer APIs without the overhead of learning a more complex standard such as
[XEP-0234: Jingle File Transfer][XEP-0234].
[XEP-0234]: https://xmpp.org/extensions/xep-0234.html
- No external dependencies
- Ability to create a …

design: add proposal for XEP-0047

---

CODE_OF_CONDUCT.md
CONTRIBUTING.md

This updates the code of conduct to be based on version 2.0 of the
Contributor Covenant
(https://www.contributor-covenant.org/version/2/0/code_of_conduct.html).

all: update the code of conduct

---

CHANGELOG.md
mux/iq.go
mux/iq_test.go
mux/mux.go
mux/mux_test.go

mux: add IQ matcher
Adding a separate IQ muxer to the mux package will allow us to easily
match based on the payload of an IQ without requiring special handling
in the standard muxer,
Fixes #18

mux: add IQ matcher

---

CHANGELOG.md
stanza/iq.go
stanza/iq_test.go

Previously the user had to do the repetative task of switching the
to/from attributes and changing the type.  While this isn't a lot of
extra work, it has to be done every time you want to reply to an IQ.
Instead it makes sense to have an easy way to simply reply to the IQ
without making an explicit copy or modifying it and without having to
jump through extra hoops.

stanza: add API for easily replying to IQs

---

internal/xmpptest/session.go
mux/mux.go
ping/ping_test.go
session.go
xtime/time_test.go

In an effort to remove the special cases around checking for stanzas that involve empty namespaces, I am experimenting with automatically wrapping testing sessions in a root element that sets a namespace and then using stricter validation everywhere else.

Namespace fixes

---

sasl_test.go

I prefer to keep tests in a separate package from the main code where
possible to ensure that the public API is what ends up being tested.
This makes it less likely that tests only test small internal pieces and
not the behavior of the package as a whole.

xmpp: move SASL tests to xmpp_test package

---

CHANGELOG.md
features.go

Previously if a required feature in a list of stream features could not
be negotiated (eg. because one of its necessary state bits wasn't set)
it would be skipped over and the stream features list would not be
marked as containing required features. This means that if no feature in
the list was marked as required, we would assume that was the end of
stream negotiation and bail out early. Instead, make sure to always
parse every feature and check if it's required, even if it can't be
negotiated. This way we know that we need to try again and negotiate one
of the required features after negotiating the optional features.
Fixes #47

xmpp: check every feature in the list for required

---

CHANGELOG.md
send_test.go
session_iq.go

Previously UnmarshalIQ would fail if there was no payload in the IQ (eg.
an empty IQ result, indicating success). Instead, skip unmarshaling in
this case.

xmpp: fix an error in UnmarshalIQ

---

carbons/handler.go
carbons/handler_test.go

This PR adds a basic handler that can be registered to handle message carbons. This API will likely change before the next release.

carbons: add handler for incoming carbons

---

CHANGELOG.md
blocklist/blocking.go
disco/items.go
roster/roster.go
roster/roster_test.go
session_iq.go

Though the types in this package contained version strings and would unmarshal version strings, roster versioning wasn't really supported. This patch adds the ability to set the version on roster requests so that we can actually support versioning.

roster: support roster versioning

---

CHANGELOG.md
disco/handler.go
disco/handler_test.go
disco/items.go
disco/items/items.go
disco/items/items_test.go
disco/items_test.go
mux/mux.go
mux/mux_test.go

This patch set allows handlers to implement an interface and respond to `disco#items` requests. All handlers are trusted to return items for all nodes.

all: allow handlers to respond to disco#items requests

---

CHANGELOG.md
doc.go
docs/overview.md
examples/echobot/echo.go
examples/im/main.go
internal/integration/integration.go
internal/integration/mellium/mellium.go
negotiator.go
session.go
session_test.go
websocket/integration_test.go
websocket/negotiator.go
websocket/ws.go

Previously the stream config was a struct and the only thing that could
be changed between stream restarts was the features we advertised.
However, we may want to change other parts of the stream config between
restarts. For example, if we figure out the users JID after the first
step we may want to look them up in the database and set the default
stream language based on their preferences.
To accomplish this we now take a stream config function instead of taking
the struct directly (and the Features field has gone back to being a
slice and is no longer a function itself).
Each time we iterate we update the config by calling the function, which
can look up properties of the session before deciding what config needs
to change.
Fixes #106

xmpp: make stream config more flexible

---

dial/dial.go
docs/dial.gv

This patch updates the docs to better show the state of dialing as it
currently stands, and simplifies the dialing algorithm by factoring out
legacy A/AAAA fallback and reworking how the TLS config is handled.

dial: simplify dialing and update docs

---

CHANGELOG.md
session.go

This patch deprecates the InSID and OutSID methods in favor of returning
the entire stream info.
In the future this will let us more easily access the stream language,
SID, namespace used, etc. and unlocks major changes throughout the rest
of the package including removing the S2S state bit among others.
Fixes #175

xmpp: add In and Out methods to session

---

blocklist/blocking_test.go
internal/stream/stream.go
internal/stream/stream_test.go
internal/xmpptest/features.go
internal/xmpptest/session.go
internal/xmpptest/session_test.go
mux/mux_test.go
negotiator.go
receipts/receipts_test.go
roster/roster_test.go
session_test.go
starttls_test.go

Previously we set the namespace depending on whether a server-to-server
value was set. However, the namespace is set in the stream and may be
other values (such as the Jabber Component namespace) as well, so just
leave this alone and let the negotiator handle it.

internal/stream: remove s2s bool from stream send

---

CHANGELOG.md
blocklist/blocking.go
delay/delay.go
delay/delay_test.go
history/history.go
mux/mux.go
mux/mux_test.go
mux/option.go
session.go
stanza/id_test.go
stanza/stanza.go

Previously we were checking if something was a stanza based on faulty
assumptions (that there were only two valid stanza namespaces) and
without precision (we'd accept it if it were either namespace or none
instead of only accepting the actual namespace used by the stream).
This PR fixes this to ensure that eg. a vulnerability that causes the
server to allow {jabber:server}message's sent over a jabber:client
stream without any of the normal security measures still won't affect
this library (hopefully).
This PR updates all locations to use the new APIs, but does not
necessarily perform the correct checks. A followup PR will be rquired to
upgrade some of the packages (eg. mux) to use the correct namespace.

all: be more strict about stanza namespaces

---

CHANGELOG.md
blocklist/blocking_test.go
carbons/handler_test.go
disco/handler_test.go
examples/im/main.go
history/history_test.go
muc/integration_test.go
muc/muc_test.go
muc/room_integration_test.go
muc/room_test.go
mux/mux.go
mux/mux_test.go
ping/integration_test.go
ping/ping_test.go
receipts/receipts_test.go
roster/roster_test.go
xtime/time_test.go

Previously anything that had a local name that looked like a stanza
("message", "iq", or "presence") would be treated as such, opening us up
to potential vulnerabilities in servers that allow a
{jabber:server}message on a jabber:client stream but don't treat it as a
stanza, for example.
Being more strict about checking namespaces helps to avoid this issue,
but does require a breaking change to the mux API.

all: add strict namespace checking to mux

---

examples/commands/go.mod
examples/commands/go.sum
examples/echobot/go.mod
examples/echobot/go.sum
examples/im/go.sum
examples/msgrepl/go.mod
examples/msgrepl/go.sum
go.mod
go.sum

Prepare for a release by bumping the dependency on mellium.im/xmlstream
to v0.15.3 and update the targeted Go version to 1.16 (the earliest
supported release).

all: bump deps and target Go version

---

session.go

The InSID and OutSID methods on Session are deprecated since v0.20.0 and can now be removed. Fixes #178
Signed-off-by: Julian Huhn <julian@huhn.dev>

xmpp: remove InSID and OutSID methods

---

.builds/validate.yml
stream/version.go

Add some missing lints that staticcheck does not run by default and fix a doc comment that was incorrect and would have triggered one of the new checks.

stream, .builds: linter fixes

---

.builds/validate.yml

Previously we checked commits based on the author in the HEAD commit,
but we need to use the author for the actual commit in case one patch set
contains commits by multiple authors.
Fixes #209

.builds: check each commit for DCO individually

---

disco/gen.go
internal/genfeature/gen.go

A few minor fixes to various packages. Typo fixes, dead code removal, and a broken file close that didn't actually matter as it's a rarely run tool that exits quickly without consuming resources anyways.

Minor fixes

---

internal/genform/gen.go
muc/integration_test.go
muc/room_integration_test.go
ping/integration_test.go

The gosec tool is complaining about several spots in gen.go, but this is
a tool that's only run on occasion by go generate and is not part of the
final build, making these issues safe.

internal/genform: ignore gosec false positives

---

.builds/validate.yml
internal/genform/gen.go

Somehow we missed this one before, probably by running a different
version of gosec locally than we do in CI.
As with the others, this is just a small codegen tool and it is okay
that it uses unsafe constructs.
**EDIT:** this also reverts a disabled lint now that the bug has been fixed.

internal/genform: fix more gosec lints

---

Makefile

These commits add all of the codegen rules to the makefile (mostly for documentation purposes) and add back the ability to generate a graphical representation of the dependency graph.
**EDIT:** I've also added a commit that fixes at least one of the broken CI stages. The others will have to come later.

make: update codegen rules and add deps.svg

---

history/integration_test.go

This adds an integration test that fetches history, checks that none was received, then fetches history again and checks that the correct number of messages were received. It does not verify anything else about the messages, just that the request worked and that the handler for the response was triggered.

history: add client side integration test

---

blocklist/blocking_test.go
disco/items_test.go
internal/stream/reader.go
internal/stream/reader_test.go
roster/roster_test.go
sasl_test.go
session.go

The stream.Reader transformer wraps every XML stream we pop from, so
moving the tracking of XML that is disallowed at the XMPP level into it
makes it easier to test and makes sure that these rules are enforced
consistently everywhere.
Fixes #126

all: move XML subset tracking into stream.Reader

---

.builds/integration.yml
internal/integration/aioxmpp/aioxmpp.go
internal/integration/aioxmpp/aioxmpp_client.py
internal/integration/aioxmpp/aioxmpp_config.ini
internal/integration/aioxmpp/config.go
internal/integration/integration.go
ping/aioxmpp_integration_test.py
ping/integration_test.go

Add a new package for running integration tests against the [`aioxmpp`] Python library.
[`aioxmpp`]: https://docs.zombofant.net/aioxmpp/devel/

internal/integration/aioxmpp: add new integration test package

---

CHANGELOG.md
session.go

While working on IBB tests the other side of the connection sent us a
payload we don't support, resulting in an error. However, I noticed the
error was showing up in the logs twice: once being sent and once being
received. It turns out we have been sending errors to ourselves instead
of the remote entity. This patch fixes that.

xmpp: write error IQ responses correctly

---

internal/integration/aioxmpp/aioxmpp_client.py

Somehow I copy/pasted and duplicated the test runner code, but we
probably only want to run the Python side of tests once.

internal/integration/aioxmpp: run tests only once

---

CHANGELOG.md
mux/mux.go
mux/mux_test.go

These two patches fix two bugs in the `mux` package. The first fixes an edge case where we would respond to unhandled IQs of type "result" with a service-unavailable error, however we should never respond to result type IQs. The second fixes an issue where an unhandled result IQ with no payload would result in the stream being disconnected. However, this is a perfectly valid thing to send (only set, get, and error IQs require payloads).

mux: fix several small bugs

---

examples/msgrepl/main.go

Inside the for loop is a return statement that causes msgrepl to crash
if the user makes an empty input. Replace return with continue.
Signed-off-by: Julian Huhn <julian@huhn.dev>

examples/msgrepl: fix crash for empty input

---

ibb/conn.go
ibb/ibb.go
ibb/ibb_test.go
ibb/integration_test.go
ibb/listen.go

This greatly simplifies the concurrency of IBB and fixes a race condition when creating, destroying, and using listeners.

ibb: simplify concurrency and fix data race

---

internal/integration/aioxmpp/aioxmpp.go
internal/integration/integration.go
internal/integration/slixmpp/slixmpp.go

Also rename tests created with the aioxmpp and slixmpp packages from
"python" to "aioxmpp" and "slixmpp" respectively.

internal/integration: allow renaming subtests

---

ibb/conn.go
ibb/ibb.go
ibb/ibb_test.go
ibb/integration_test.go
ibb/payloads.go
ibb/slixmpp_integration_test.py

This patch set adds the ability to restrict buffer growth on IBB streams. Its merge is blocked until [poezio@lab.louiz.org/slixmpp#179](https://lab.louiz.org/poezio/slixmpp/-/merge_requests/179) is merged.

ibb: add max buffer size

---

CHANGELOG.md
websocket/ws.go

Previously after fetching a websocket connection endpoint from a DNS TXT
record we were verifying the certificate against the name fetched from
the record. This is incorrect and results in the ability to MITM the
connection because if DNS is spoofed and the WSS endpoint is changed to
evil.example.net we would verify that evil.example.net presented a valid
certificate for itself, but not for good.example.net (or whatever the
original address was expecting). Instead, verify the original address.
This issue has been given CVE ID `CVE-2022-24968` and a write up is available here: https://mellium.im/cve/cve-2022-24968/

websocket: fix incorrect TLS host verification

---

CHANGELOG.md
internal/discover/lookup.go
internal/discover/lookup_test.go
websocket/ws.go

This removes the obsoleted DNS TXT record lookup method and fixes the
broken XRD file lookup.

internal/discover: rewrite WebSocket lookups

---

CHANGELOG.md
mux/mux.go
mux/mux_test.go
mux/option.go

Previously we could only add features when adding a handler.
Some features, however, may not actually correspond to any particular
query or data transmission and are informational only.
This adds the ability to register types other than the handler types
that implement features or identities.

mux: add ability to add features without handler

---

disco/caps.go
disco/caps_test.go

This patch uses the new [`crypto`] package for entity caps, ensuring that we only use supported algorithms and that marshaling and unmarshaling is correct.
[`crypto`]: https://pkg.go.dev/mellium.im/xmpp/crypto

disco: use the new crypto package for caps

---

CHANGELOG.md
ibb/ibb.go
ibb/ibb_test.go
ibb/listen.go

Most IBB sessions will be negotiated out of band, however there was
previously no API for accepting a specific pre-negotiated session.
Fixes #240

ibb: add API to listen for specific connections

---

blocklist/blocking.go
doc.go
examples/echobot/main.go
internal/discover/lookup.go
internal/integration/aioxmpp/aioxmpp.go
internal/integration/integration.go
internal/integration/prosody/prosody.go
internal/integration/slixmpp/slixmpp.go
jid/doc.go
muc/muc.go
oob/oob.go
stanza/doc.go
stream/error.go
styling/styling.go

Some changes were made to documentation comments in Go 1.19 including
adding "#" before headers (instead of detecting them with a heuristic),
and indentation using tabs.
This patch is the result of running "gofmt -s -w ." in the project root.
Fixes #298

all: run gofmt for Go 1.19 doc comments
